# Internal only; exposed to the outside through Traefik.
apiVersion: v1
kind: Service
metadata:
  name: query
  labels:
    app: query
spec:
  type: ClusterIP
  selector:
    app: query
  ports:
    - name: http
      port: 19090
      targetPort: 19090
