version: 2

project_name: optikk

before:
  hooks:
    - go mod tidy

builds:
  - id: optikk
    binary: optikk
    main: .
    env:
      - CGO_ENABLED=0
    goos: [darwin, linux]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -buildid= -X github.com/optikklabs/optikk/cmd.version={{ .Version }} -X github.com/optikklabs/optikk/cmd.commit={{ .ShortCommit }} -X github.com/optikklabs/optikk/cmd.date={{ .Date }}

archives:
  - id: optikk
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - NOTICE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
