apiVersion: v1
kind: Service
metadata:
  name: mq
  labels:
    app: mq
spec:
  selector:
    app: mq
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: metrics
      port: 7080
      targetPort: 7080
