// Package agentdocs is the single source of truth for how an AI agent should
// operate the optikk CLI. One embedded template renders every surface — the
// Claude Code skill file, the AGENTS.md section, and the hosted guide — and
// the example playbooks double as data for `optikk agent schema`, so the
// documentation and the schema cannot drift apart.
package agentdocs

import (
	_ "embed"
	"fmt"
	"strings"
	"text/template"

	"github.com/optikklabs/optikk/internal/endpoint"
)

//go:embed guide.md.tmpl
var guideTmpl string

//go:generate go run ./gen -o ../../AGENTS.md

// RepoDocVersion stamps the checked-in AGENTS.md, which is regenerated by
// `go generate ./...` rather than at build time.
const RepoDocVersion = "main"

// Example is one goal-oriented playbook: the steps an agent runs, in order.
type Example struct {
	Goal  string   `json:"goal"`
	Steps []string `json:"steps"`
}

// Examples returns the canonical playbooks, shared by the rendered guide and
// the agent schema.
func Examples() []Example {
	return []Example{
		{
			Goal: "Onboard a new account and confirm telemetry flows",
			Steps: []string{
				"optikk onboard --agent --email … --password … --name … --org … --accept-terms  (only after the user agrees to the ToS)",
				"set OTEL_EXPORTER_OTLP_ENDPOINT and OTEL_EXPORTER_OTLP_HEADERS from the response's otlp field, instrument the app, generate traffic",
				"optikk verify --agent --from 15m  (loop until exit 0)",
			},
		},
		{
			Goal: "Find why a service is slow",
			Steps: []string{
				"optikk services list --agent --from 1h  (RED overview: rate, errors, latency percentiles)",
				"optikk services summary --agent --service <svc> --from 1h",
				"optikk traces search --agent -q \"service:<svc>\" --from 1h --limit 20",
				"optikk traces critical-path <trace-id> --agent",
				"optikk logs trace <trace-id> --agent",
				"optikk infra hosts --agent  and  optikk saturation db-latency --agent  (resource correlation)",
			},
		},
		{
			Goal: "Investigate an error spike",
			Steps: []string{
				"optikk errors list --agent --service <svc> --from 1h",
				"optikk errors latest <group-id> --agent  (message + stacktrace)",
				"optikk traces get <sample_trace_id> --agent",
				"optikk logs trace <sample_trace_id> --agent",
				"optikk errors timeseries <group-id> --agent  (when did it start?)",
			},
		},
	}
}

// ExitCodes maps each process exit code to its meaning, mirroring the clierr
// taxonomy.
func ExitCodes() map[string]string {
	return map[string]string{
		"0": "success",
		"1": "error",
		"2": "usage: bad or missing flags",
		"3": "auth: run optikk auth login (or set OPTIKK_TOKEN)",
		"4": "network: API unreachable",
		"5": "api: server rejected the request (see api_code)",
	}
}

// generatedHeader stamps every rendered file so readers know not to edit it.
func generatedHeader(version string) string {
	return fmt.Sprintf("<!-- generated by optikk agent setup (%s); re-run to refresh -->\n\n", version)
}

// Guide renders the full agent guide body.
func Guide(version string) (string, error) {
	t, err := template.New("guide").Parse(guideTmpl)
	if err != nil {
		return "", err
	}
	codes := ExitCodes()
	line := make([]string, 0, len(codes))
	for _, c := range []string{"0", "1", "2", "3", "4", "5"} {
		line = append(line, c+" = "+codes[c])
	}
	var b strings.Builder
	err = t.Execute(&b, struct {
		Version       string
		DocsURL       string
		Examples      []Example
		ExitCodesLine string
	}{version, endpoint.DocsURL, Examples(), strings.Join(line, " · ")})
	if err != nil {
		return "", err
	}
	return generatedHeader(version) + b.String(), nil
}

// Skill renders the guide as a Claude Code skill file (with frontmatter).
func Skill(version string) (string, error) {
	body, err := Guide(version)
	if err != nil {
		return "", err
	}
	frontmatter := "---\n" +
		"name: optikk\n" +
		"description: Operate the Optikk observability platform via the optikk CLI — signup, team onboarding, and performance/error investigation.\n" +
		"---\n\n"
	return frontmatter + body, nil
}

// Markers delimit the optikk-owned block inside a shared AGENTS.md, so
// re-running setup replaces the block instead of appending a duplicate.
const (
	BeginMarker = "<!-- BEGIN optikk-cli -->"
	EndMarker   = "<!-- END optikk-cli -->"
)

// AgentsSection renders the guide wrapped in replace-or-append markers for
// embedding into a project's AGENTS.md.
func AgentsSection(version string) (string, error) {
	body, err := Guide(version)
	if err != nil {
		return "", err
	}
	return BeginMarker + "\n" + body + "\n" + EndMarker + "\n", nil
}

// UpsertAgentsSection replaces the marked block in existing (or appends one),
// returning the updated document. It is idempotent.
func UpsertAgentsSection(existing, version string) (string, error) {
	section, err := AgentsSection(version)
	if err != nil {
		return "", err
	}
	begin := strings.Index(existing, BeginMarker)
	end := strings.Index(existing, EndMarker)
	if begin >= 0 && end > begin {
		return existing[:begin] + strings.TrimSuffix(section, "\n") + existing[end+len(EndMarker):], nil
	}
	if existing == "" {
		return section, nil
	}
	return strings.TrimRight(existing, "\n") + "\n\n" + section, nil
}
