apiVersion: v1
kind: Service
metadata:
  name: ingest
  labels:
    app: ingest
spec:
  selector:
    app: ingest
  ports:
    - name: otlp-grpc
      port: 18317
      targetPort: 18317
    - name: otlp-http
      port: 18318
      targetPort: 18318
    - name: metrics
      port: 18090
      targetPort: 18090
