apiVersion: v1
kind: Service
metadata:
  name: ingest
  labels:
    app: ingest
spec:
  selector:
    app: ingest
  ports:
    - name: otlp-grpc
      port: 4318
      targetPort: 4318
    - name: metrics
      port: 18090
      targetPort: 18090
